# Generated by Django 4.2.5 on 2023-10-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_customuser_email_alter_customuser_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(max_length=13, unique=True),
        ),
    ]
